tenant: "public"
namespace: "default"
name: "secrets-printer"
className: "secrets_printer"
inputs: ["public/default/secrets-trigger"]
autoAck: true
parallelism: 1
resources:
  cpu: 0.5
  ram: 536870912
  disk: 536870912
secrets:
  username:
    path: "pulsar/database/config"
    key: username
  password:
    path: "pulsar/database/config"
    key: password
customRuntimeOptions: >-
  {
    "serviceAccountName": "pf-secrets-printer"
  }
